# Generated by Django 4.2.30 on 2026-07-26 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_duration_days', models.IntegerField(default=7)),
                ('extended_duration_days', models.IntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('trade_type', models.CharField(max_length=10)),
                ('entry_date', models.CharField(max_length=15)),
                ('entry_price', models.FloatField()),
                ('quantity', models.IntegerField(default=10)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('entry_reason', models.TextField(blank=True, default='')),
                ('exit_date', models.CharField(blank=True, max_length=15, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Active', max_length=15)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
