# Generated by Django 4.2.30 on 2026-08-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_userprofile_pro_expires_at_usernotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stock_symbol', models.CharField(max_length=20)),
                ('theme', models.CharField(max_length=50)),
                ('theme_display', models.TextField(blank=True, default='')),
                ('twitter_thread_json', models.TextField(default='[]')),
                ('linkedin_post', models.TextField(blank=True, default='')),
                ('telegram_digest', models.TextField(blank=True, default='')),
                ('youtube_shorts_script_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
