# Generated by Django 4.2.30 on 2026-08-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0004_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='q1_bearish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='q1_bullish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='q1_wait',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='q2_bearish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='q2_bullish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='q2_wait',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='q3_bearish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='q3_bullish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='q3_wait',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='question_1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='question_2',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='question_3',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_profiles', to='screener.communitypost'),
        ),
    ]
