# Generated by Django 4.2.30 on 2026-09-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0005_communitypost_q1_bearish_communitypost_q1_bullish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=25, unique=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('market_cap_cr', models.FloatField(blank=True, null=True)),
                ('magic_score', models.IntegerField(db_index=True, default=0)),
                ('piotroski_score', models.IntegerField(default=0)),
                ('peg_ratio', models.FloatField(blank=True, null=True)),
                ('roce_pct', models.FloatField(blank=True, null=True)),
                ('debt_equity', models.FloatField(blank=True, null=True)),
                ('ebit_cr', models.FloatField(blank=True, null=True)),
                ('net_profit_cr', models.FloatField(blank=True, null=True)),
                ('interest_coverage', models.FloatField(blank=True, null=True)),
                ('score_breakdown_json', models.TextField(default='{}')),
                ('yearly_trends_json', models.TextField(default='[]')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
