# Generated by Django 4.2.30 on 2026-09-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0006_stockfundamental'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfundamental',
            name='net_margin_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamental',
            name='peg_is_fallback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockfundamental',
            name='peg_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
