# Generated by Django 4.2.30 on 2026-09-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0007_stockfundamental_net_margin_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfundamental',
            name='industry',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='stockfundamental',
            name='sector',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
    ]
