# Generated by Django 4.2.30 on 2026-09-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0008_stockfundamental_industry_stockfundamental_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockfundamental',
            options={'ordering': ['-magic_score', 'ticker'], 'verbose_name': 'Stock Fundamental', 'verbose_name_plural': 'Stock Fundamentals'},
        ),
    ]
