# Generated by Django 4.2.30 on 2026-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0009_alter_stockfundamental_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfundamental',
            name='macd_crossover_date',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='stockfundamental',
            name='macd_signal',
            field=models.CharField(blank=True, db_index=True, default='Neutral', max_length=30),
        ),
        migrations.AddField(
            model_name='stockfundamental',
            name='rsi_crossover_date',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='stockfundamental',
            name='rsi_signal',
            field=models.CharField(blank=True, db_index=True, default='Neutral', max_length=30),
        ),
    ]
