# Generated by Django 4.2.30 on 2026-10-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0010_stockfundamental_macd_crossover_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('golden_cross', 'Moving Average Crossover'), ('rsi_breakout', 'RSI Momentum Breakout'), ('macd_cross', 'MACD Velocity Crossover'), ('volatility_squeeze', 'Volatility Squeeze Breakout'), ('pullback', 'Trend Pullback & Re-test')], default='golden_cross', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('parameters_json', models.TextField(default='{}', help_text="e.g. {'fast_ma': 45, 'slow_ma': 195, 'ma_type': 'SMA'}")),
                ('total_signals', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('avg_return_pct', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recommendation Strategy',
                'verbose_name_plural': 'Recommendation Strategies',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TradeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=25)),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('direction', models.CharField(choices=[('BUY', 'Buy / Long'), ('SELL', 'Sell / Short')], default='BUY', max_length=10)),
                ('entry_price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_price_triggered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trailing_stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_reward_ratio', models.CharField(default='1:2.5', max_length=20)),
                ('recommended_allocation_pct', models.FloatField(default=5.0)),
                ('max_risk_pct', models.FloatField(default=1.5)),
                ('status', models.CharField(choices=[('draft', 'Draft (Review Pending)'), ('pending', 'Pending Entry (Wait for Entry Range)'), ('active', 'Active (In Progress)'), ('target_1_hit', 'Target 1 Reached (Partial Profit Booked)'), ('target_2_hit', 'Target 2 Reached (Holding Runners)'), ('completed_profit', 'Closed in Profit'), ('sl_hit', 'Stop Loss Hit (Closed)'), ('cancelled', 'Cancelled / Invalidated')], db_index=True, default='draft', max_length=25)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('holding_days', models.IntegerField(default=0)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('realized_gain_loss_pct', models.FloatField(blank=True, null=True)),
                ('is_winning_trade', models.BooleanField(blank=True, null=True)),
                ('thesis_summary', models.TextField(blank=True, default='')),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='trade_charts/%Y/%m/')),
                ('ai_conviction_score', models.IntegerField(default=85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='screener.recommendationstrategy')),
            ],
            options={
                'verbose_name': 'Trade Recommendation',
                'verbose_name_plural': 'Trade Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=25)),
                ('new_status', models.CharField(max_length=25)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='screener.traderecommendation')),
            ],
            options={
                'verbose_name': 'Trade Update Log',
                'verbose_name_plural': 'Trade Update Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
