# Generated by Django 4.2.30 on 2026-10-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0012_seed_recommendation_strategies'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecommendation',
            name='strategy_audit_json',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
